FROM maven:3.9.6-eclipse-temurin-21 AS builder  
WORKDIR /app
COPY pom.xml .
COPY src  ./src
RUN mvn clean package -DskipTests
# ============== stage:2 run==================
FROM eclipse-temurin:21-jre 
WORKDIR /app
COPY --from=builder /app/target/payment-se/app/target/payment-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8083
ENTRYPOINT [ "java", "-jar", "app.jar" ]
