spring.application.name=log-processing-service

server.port=8083

# =========================
# MYSQL
# =========================
spring.datasource.url=jdbc:mysql://localhost:3307/distributed_log_monitoring
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# KAFKA
# =========================
spring.kafka.bootstrap-servers=localhost:9092

# Group ID change kar do taaki purane offsets na padhe
spring.kafka.consumer.group-id=log-group-v2

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# ignore the type header of kafka
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# use the local dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.log_processing_service.DTO.LogMessage

spring.kafka.consumer.properties.spring.json.trusted.packages=*